# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Record',
        ),
    ]
