# dependancies for development environment
# run: $ conda env create -f environment.yml

name: datawaves
channels:
  - conda-forge
dependencies:
  - python=3.5
  - bokeh
  - django
  - jupyter
  - numpy
  - scipy
  - numba
  - matplotlib
  - psutil
  - pandas
  # if postgres
  - psycopg2
  - fiona
  - pyproj
  - rasterio
  - seaborn
  - mpld3
  - statsmodels
  - pymc3
  - pillow
  - h5py
  - scikit-learn

# The following packages must be pip installed:
# pyprind
# sox
# mysqlclient (if mysql)
# nacoustik
# geopandas
# overpy
# django-extensions
# pymorton