# dependancies for development environment
# run: $ conda env create

name: datawaves
dependencies:
  - bokeh
  - django
  - jupyter
  - numpy
  - scipy
  - numba
  - matplotlib
  - psutil
  - pandas
  # if postgres
  - psycopg2
  - fiona
  - pyproj
  - rasterio
  - seaborn
  - mpld3
  - statsmodels
  - pymc3

# The following packages must be pip installed:
# pyprind
# sox
# mysqlclient (if mysql)
# nacoustik
# geopandas