# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('citation', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('microphone', models.CharField(blank=True, max_length=250)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lat', models.FloatField(blank=True)),
                ('lon', models.FloatField(blank=True)),
                ('elevation', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('sound_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('quality', models.IntegerField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('filepath', models.CharField(max_length=1000)),
                ('MD5_hash', models.CharField(blank=True, max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('collection_id', models.ForeignKey(db_column='collection_id', on_delete=django.db.models.deletion.CASCADE, to='database.Collection')),
                ('sensor_id', models.ForeignKey(db_column='sensor_id', on_delete=django.db.models.deletion.CASCADE, to='database.Sensor')),
                ('site_id', models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.CASCADE, to='database.Site')),
            ],
        ),
    ]
