# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20160827_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collection_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='site_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='sound',
            old_name='sound_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='collection_id',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='sensor_id',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='site_id',
        ),
        migrations.AddField(
            model_name='setting',
            name='sound_preview_directory',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='setting',
            name='spectrogram_image_directory',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='sound',
            name='collection',
            field=models.ForeignKey(db_column='collection', default=1, on_delete=django.db.models.deletion.CASCADE, to='database.Collection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sound',
            name='sensor',
            field=models.ForeignKey(db_column='sensor', default=1, on_delete=django.db.models.deletion.CASCADE, to='database.Sensor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sound',
            name='site',
            field=models.ForeignKey(db_column='site', default=1, on_delete=django.db.models.deletion.CASCADE, to='database.Site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='sound_directory',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
