# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20160827_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='sensor_id',
            new_name='id',
        ),
    ]
