# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20160912_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='custom_filepath',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
