# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20161026_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='custom_filepath',
            field=models.CharField(max_length=1000),
        ),
    ]
