# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 15:45
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_site_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='shape',
            field=django.contrib.gis.db.models.fields.PointField(srid=31254),
        ),
    ]
