# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20161027_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='shape',
            new_name='geometry',
        ),
    ]
