# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0004_auto_20160827_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('call', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoundscapeSpec',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('frequency_power', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('call', models.ForeignKey(db_column='call', null=True, on_delete=django.db.models.deletion.SET_NULL, to='metrics.Call')),
                ('sound', models.ForeignKey(db_column='sound', on_delete=django.db.models.deletion.CASCADE, to='database.Sound')),
            ],
        ),
    ]
