# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_soundexposurelevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name_plural': 'analyses'},
        ),
        migrations.AlterField(
            model_name='analysis',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
