# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_auto_20160913_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundexposurelevel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='soundscapespec',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
