# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20160912_1324'),
        ('metrics', '0006_acousticcomplexityindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioacousticIndex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bai_left', models.FloatField()),
                ('bai_right', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(db_column='analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, to='metrics.Analysis')),
                ('sound', models.ForeignKey(db_column='sound', on_delete=django.db.models.deletion.CASCADE, to='database.Sound')),
            ],
            options={
                'verbose_name_plural': 'bioacoustic complexity indices',
            },
        ),
        migrations.CreateModel(
            name='NDSI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ndsi_left', models.FloatField()),
                ('ndsi_right', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(db_column='analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, to='metrics.Analysis')),
                ('sound', models.ForeignKey(db_column='sound', on_delete=django.db.models.deletion.CASCADE, to='database.Sound')),
            ],
            options={
                'verbose_name': 'NDSI',
                'verbose_name_plural': 'NDSIs',
            },
        ),
    ]
