# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0008_powerspectrumsum'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndsi',
            name='anthrophony_left',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ndsi',
            name='anthrophony_right',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ndsi',
            name='biophony_left',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ndsi',
            name='biophony_right',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
