# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20161101_0033'),
        ('metrics', '0009_auto_20170118_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundExposureLevelAdvanced',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anthrophony', models.FloatField()),
                ('biophony', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(db_column='analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, to='metrics.Analysis')),
                ('sound', models.ForeignKey(db_column='sound', on_delete=django.db.models.deletion.CASCADE, to='database.Sound')),
            ],
        ),
        migrations.CreateModel(
            name='SoundExposureLevelSimple',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sel', models.CharField(max_length=500)),
                ('anthrophony', models.FloatField()),
                ('biophony', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(db_column='analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, to='metrics.Analysis')),
                ('sound', models.ForeignKey(db_column='sound', on_delete=django.db.models.deletion.CASCADE, to='database.Sound')),
            ],
        ),
    ]
