# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-08 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0011_soundscaperatio'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundscaperatio',
            name='biophony_count',
            field=models.IntegerField(null=True),
        ),
    ]
