# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 18:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shape', django.contrib.gis.db.models.fields.MultiPolygonField(srid=31254)),
            ],
            options={
                'verbose_name_plural': 'Boundaries',
            },
        ),
    ]
