# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 19:15
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='shape',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=31254),
        ),
    ]
