# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_samplelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplelocation',
            name='landcover',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='samplelocation',
            name='naturalness',
            field=models.FloatField(blank=True),
        ),
    ]
