# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:05
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20161031_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplelocation',
            name='shape',
            field=django.contrib.gis.db.models.fields.PointField(srid=31254),
        ),
    ]
