# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_auto_20161031_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boundary',
            old_name='shape',
            new_name='geometry',
        ),
        migrations.RenameField(
            model_name='samplelocation',
            old_name='shape',
            new_name='geometry',
        ),
    ]
