# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_auto_20161101_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('filepath', models.CharField(max_length=250)),
            ],
        ),
    ]
