# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_raster'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandCoverType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
    ]
