# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 18:41
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscape', '0002_naturalnessarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_type', models.IntegerField()),
                ('shape', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
