# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 19:36
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landscape', '0003_landcover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landcover',
            name='shape',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=31254),
        ),
    ]
