# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscape', '0005_auto_20161104_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandCoverTypeMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lisa', models.IntegerField()),
                ('corine', models.IntegerField()),
            ],
        ),
    ]
